const assert = require("node:assert/strict");
const { createConsentCryptoProof, verifyConsentCryptoProof, createHistoricalConsentEvidenceProof, verifyHistoricalConsentEvidenceProof } = require("../../.tmp/consent-security/consent-proof.js");
const { hashConsentSessionToken, consentSessionIsActive } = require("../../.tmp/consent-security/consent-session-core.js");
const claims = { v: 2, consentId: "consent_1", websiteId: "site_1", policyVersionId: "policy_1", status: "accepted", choice: "accept-all", jurisdiction: "EEA", decisions: [{ purposeId: "analytics", vendorId: null, granted: true }], consentedAt: "2026-09-29T10:00:00.000Z", sessionId: "session_1" };
process.env.CONSENT_PROOF_KEYS = "key-2:secret-two,key-1:secret-one";
const proof = createConsentCryptoProof(claims, new Date("2026-09-29T10:00:01Z"));
assert.equal(proof.proofVersion, 2); assert.equal(proof.keyId, "key-2"); assert.equal(verifyConsentCryptoProof({ claims, proof }).intact, true);
process.env.CONSENT_PROOF_KEYS = "key-3:secret-three,key-2:secret-two,key-1:secret-one";
assert.equal(verifyConsentCryptoProof({ claims, proof }).intact, true, "historical key remains verifiable after rotation");
for (const changed of [{ ...claims, consentId: "altered" }, { ...claims, policyVersionId: "altered" }, { ...claims, consentedAt: "2026-09-29T10:01:00.000Z" }, { ...claims, jurisdiction: "US-CA" }]) assert.equal(verifyConsentCryptoProof({ claims: changed, proof }).intact, false);
assert.equal(verifyConsentCryptoProof({ claims, proof: { ...proof, signature: "0".repeat(64) } }).intact, false);
assert.equal(verifyConsentCryptoProof({ claims, proof: { ...proof, keyId: "unknown-key" } }).intact, false);
const history = { consentId: "consent_1", status: "accepted", decision: true, timestamp: claims.consentedAt };
const historical = createHistoricalConsentEvidenceProof(history);
assert.equal(verifyHistoricalConsentEvidenceProof({ evidence: history, hash: historical.hash, signature: historical.signature, keyId: historical.keyId }).intact, true);
assert.equal(verifyHistoricalConsentEvidenceProof({ evidence: { ...history, status: "withdrawn" }, hash: historical.hash, signature: historical.signature, keyId: historical.keyId }).intact, false);
const token = "A".repeat(43); assert.notEqual(hashConsentSessionToken(token), token); assert.equal(hashConsentSessionToken(token).length, 64);
const now = new Date("2026-09-29T10:00:00Z"); assert.equal(consentSessionIsActive({ status: "active", expiresAt: new Date("2026-09-29T10:01:00Z") }, now), true); assert.equal(consentSessionIsActive({ status: "active", expiresAt: now }, now), false); assert.equal(consentSessionIsActive({ status: "revoked", expiresAt: new Date("2026-09-30T00:00:00Z") }, now), false);
console.log("Consent Phase 4 proof/session tests passed");
