/**
 * Production security headers and dashboard CSRF origin checks.
 *
 * CSP for HTML documents is generated by Clerk `clerkMiddleware`
 * (`contentSecurityPolicy.strict`) so Clerk FAPI, Cloudflare challenges,
 * and nonce/`strict-dynamic` stay in sync with `@clerk/nextjs`.
 */

export const PERMISSIONS_POLICY = [
  "accelerometer=()",
  "attribution-reporting=()",
  "autoplay=()",
  "bluetooth=()",
  "camera=()",
  "compute-pressure=()",
  "display-capture=()",
  "encrypted-media=()",
  "fullscreen=(self)",
  "geolocation=()",
  "gyroscope=()",
  "hid=()",
  "identity-credentials-get=()",
  "idle-detection=()",
  "interest-cohort=()",
  "magnetometer=()",
  "microphone=()",
  "midi=()",
  "otp-credentials=()",
  "payment=()",
  "picture-in-picture=()",
  "publickey-credentials-get=()",
  "screen-wake-lock=()",
  "serial=()",
  "storage-access=()",
  "usb=()",
  "window-management=()",
  "xr-spatial-tracking=()",
].join(", ");

export const BASELINE_SECURITY_HEADERS: Record<string, string> = {
  "X-Content-Type-Options": "nosniff",
  "Referrer-Policy": "strict-origin-when-cross-origin",
  "X-Frame-Options": "SAMEORIGIN",
  "Permissions-Policy": PERMISSIONS_POLICY,
  "Cross-Origin-Opener-Policy": "same-origin",
  "X-Permitted-Cross-Domain-Policies": "none",
  "X-XSS-Protection": "0",
  "Origin-Agent-Cluster": "?1",
};

export const HSTS_HEADER_VALUE = "max-age=63072000; includeSubDomains; preload";

/** Clerk `contentSecurityPolicy.strict` merge — extra directives beyond Clerk defaults. */
export const CLERK_CSP_EXTRA_DIRECTIVES: Record<string, string[]> = {
  "base-uri": ["self"],
  "object-src": ["none"],
  "font-src": ["self", "data:"],
  "media-src": ["self"],
  "img-src": ["self", "data:", "blob:", "https:"],
  "frame-ancestors": ["self"],
  // Banner studio previews customer sites in an iframe (any http(s) origin).
  "frame-src": ["https:"],
};

export function shouldSendHsts(protocol: string, forwardedProto: string | null): boolean {
  if (process.env.NODE_ENV !== "production") return false;
  const proto = (forwardedProto ?? protocol).replace(/:$/, "").toLowerCase();
  return proto === "https";
}

export function isPublicCrossOriginApiPath(pathname: string): boolean {
  if (pathname === "/api/health" || pathname === "/api/health/ready") return true;
  if (pathname === "/api/rights-request" || pathname.startsWith("/api/rights-request/")) return true;
  if (pathname === "/api/age-assurance" || pathname.startsWith("/api/age-assurance/")) return true;
  if (pathname === "/api/guardian-consent" || pathname.startsWith("/api/guardian-consent/")) return true;
  if (pathname.startsWith("/api/cron/")) return true;
  if (pathname.startsWith("/api/webhooks/clerk")) return true;
  if (pathname.startsWith("/api/webhooks/stripe")) return true;
  if (pathname.startsWith("/api/v1/")) return true;
  if (pathname.startsWith("/api/agent/")) return true;
  if (pathname.startsWith("/api/sdk/")) return true;
  if (pathname === "/api/consent/record" || pathname.startsWith("/api/consent/record/")) return true;
  if (pathname === "/api/consent/withdraw" || pathname.startsWith("/api/consent/withdraw/")) return true;
  if (pathname === "/api/consent/policy" || pathname.startsWith("/api/consent/policy/")) return true;
  return false;
}

export function hasMachineBearerAuth(request: Request): boolean {
  return /^Bearer\s+\S+/i.test(request.headers.get("authorization") ?? "");
}

export function isStateChangingMethod(method: string): boolean {
  const m = method.toUpperCase();
  return m === "POST" || m === "PUT" || m === "PATCH" || m === "DELETE";
}

/**
 * Cookie-authenticated dashboard APIs need CSRF origin checks.
 * Public SDK/consent/rights-request POSTs are intentionally cross-origin
 * and use siteKey/websiteId, not Clerk session cookies.
 */
export function shouldEnforceCsrfOrigin(method: string, pathname: string): boolean {
  if (!isStateChangingMethod(method)) return false;
  if (!pathname.startsWith("/api/")) return false;
  if (isPublicCrossOriginApiPath(pathname)) return false;
  return true;
}

function extraAllowedOrigins(): string[] {
  return (process.env.CMP_CSRF_ALLOWED_ORIGINS ?? "")
    .split(",")
    .map((value) => value.trim())
    .filter(Boolean);
}

export function originIsAllowed(origin: string, requestOrigin: string): boolean {
  if (origin === requestOrigin) return true;
  return extraAllowedOrigins().includes(origin);
}

export function isTrustedDashboardMutation(input: {
  origin: string | null;
  referer: string | null;
  secFetchSite: string | null;
  requestOrigin: string;
}): boolean {
  const site = (input.secFetchSite ?? "").toLowerCase();
  if (site === "cross-site") return false;
  if (site === "same-origin") return true;

  if (input.origin) {
    try {
      return originIsAllowed(new URL(input.origin).origin, input.requestOrigin);
    } catch {
      return false;
    }
  }

  if (input.referer) {
    try {
      return originIsAllowed(new URL(input.referer).origin, input.requestOrigin);
    } catch {
      return false;
    }
  }

  return false;
}

export function applyBaselineSecurityHeaders(
  headers: Headers,
  meta: { protocol: string; forwardedProto: string | null },
): void {
  for (const [key, value] of Object.entries(BASELINE_SECURITY_HEADERS)) {
    headers.set(key, value);
  }
  if (shouldSendHsts(meta.protocol, meta.forwardedProto)) {
    headers.set("Strict-Transport-Security", HSTS_HEADER_VALUE);
  }
}
