-- This generated schema snapshot duplicated objects already created by
-- migrations 0033_data_principal_requests through 0039_continuous_scanner_analytics.
-- Keep the migration ordinal for databases that recorded it, but do not rerun
-- non-idempotent CREATE TABLE / ADD CONSTRAINT statements on clean installs.
