import { and, eq } from "drizzle-orm";
import { NextResponse } from "next/server";
import { requireDashboardContext } from "@/lib/bootstrap-current-context";
import { db } from "@/db";
import { consentSessions } from "@/db/schema/consent-sessions";
import { privacyEvents } from "@/db/schema/privacy-events";
import { revokeConsentSession } from "@/lib/consent-session";
import { roles } from "@/db/schema/roles";
import { requireOperatorRole } from "@/lib/org-roles";
export async function GET(_request: Request, { params }: { params: Promise<{ sessionId: string }> }) { try { const context = await requireDashboardContext(); const { sessionId } = await params; const [session] = await db.select().from(consentSessions).where(and(eq(consentSessions.id, sessionId), eq(consentSessions.organizationId, context.organization.id))).limit(1); if (!session) return NextResponse.json({ success: false, message: "Session not found" }, { status: 404 }); const events = await db.select().from(privacyEvents).where(and(eq(privacyEvents.sessionId, session.id), eq(privacyEvents.organizationId, context.organization.id))).orderBy(privacyEvents.occurredAt); return NextResponse.json({ success: true, session: { id: session.id, websiteId: session.websiteId, consentRecordId: session.consentRecordId, policyVersionId: session.policyVersionId, status: session.expiresAt <= new Date() && session.status === "active" ? "expired" : session.status, decisionCount: session.decisionCount, expiresAt: session.expiresAt, revokedAt: session.revokedAt, createdAt: session.createdAt }, events }); } catch { return NextResponse.json({ success: false, message: "Unauthorized" }, { status: 401 }); } }
export async function DELETE(_request: Request, { params }: { params: Promise<{ sessionId: string }> }) { try { const context = await requireDashboardContext(); const [role] = await db.select({ name: roles.name }).from(roles).where(eq(roles.id, context.membership.roleId)).limit(1); const roleError = requireOperatorRole(role?.name); if (roleError) return roleError; const { sessionId } = await params; const revoked = await revokeConsentSession(sessionId, context.organization.id); if (!revoked.length) return NextResponse.json({ success: false, message: "Active session not found" }, { status: 404 }); await db.insert(privacyEvents).values({ organizationId: context.organization.id, websiteId: revoked[0].websiteId, sessionId, eventType: "consent.session_revoked", provenance: "observed", payload: { reason: "organization_action" } }); return NextResponse.json({ success: true, status: "revoked" }); } catch { return NextResponse.json({ success: false, message: "Unauthorized" }, { status: 401 }); } }
