/** Prerequisite text for each module, from DPDP_30_Modules_Prerequisites.pdf. */
export const MODULE_PREREQUISITES: Record<number, string> = {
  1: "Participants should have a basic understanding of personal information, digital systems and organisational data handling. They should be familiar with how organisations collect, store, use and share information relating to customers, employees, students, citizens or other individuals, as well as the basic concepts of privacy, confidentiality, information security and responsible data management.",
  2: "Participants should have a basic understanding of Indian legislation, statutory provisions, Acts, Rules, notifications and regulatory compliance. They should understand that an Act establishes the primary legal framework while Rules provide operational requirements and procedures, and should be comfortable reading legal provisions and translating them into organisational compliance requirements.",
  3: "Participants should understand the basic difference between an individual whose data is being processed, an organisation determining the purpose and means of processing, and an external service provider processing data on behalf of an organisation. Familiarity with basic concepts such as personal data, processing, consent, privacy and cybersecurity will help participants understand the statutory terminology used throughout the framework.",
  4: "Participants should have a basic understanding of how organisations collect and process personal data, where such processing takes place and how digital services may operate across geographical boundaries. They should also understand the distinction between applicability of a law and situations where a specific statutory exemption may apply.",
  5: "Participants should understand what constitutes information relating to an identifiable individual and have basic familiarity with digital records such as databases, applications, emails, documents, cloud storage, logs and analytics systems. Knowledge of common identifiers and the difference between structured and unstructured information will help participants identify digital personal data within organisational environments.",
  6: "Participants should understand the concept of an individual to whom personal data relates and have basic familiarity with customer, employee, citizen or user interactions with organisations. They should also have a basic understanding of identity verification, personal-data rights, correction, erasure and grievance mechanisms.",
  7: "Participants should understand how an organisation decides why and how personal data is processed and how such processing supports business or institutional activities. Basic knowledge of organisational accountability, business processes, privacy responsibilities and the distinction between an organisation and its technology or service providers will help in understanding the role of a Data Fiduciary.",
  8: "Participants should understand outsourcing, cloud services, managed services, technology vendors and other situations where an external entity processes personal data on behalf of an organisation. Basic knowledge of vendor management, contracts, access control, confidentiality, cybersecurity and third-party risk will help participants understand Data Processor responsibilities.",
  9: "Participants should have a basic understanding of consent as a mechanism through which an individual permits processing of personal data for a stated purpose. They should be familiar with digital forms, checkboxes, permissions, subscriptions, user interfaces and the distinction between voluntary consent and information or permissions that may be required for providing a service.",
  10: "Participants should understand the basic purpose of a privacy notice and how organisations communicate information about the collection and use of personal data. Familiarity with websites, mobile applications, registration forms, consent screens and customer communications will help participants understand how transparency and informed consent should operate in practice.",
  11: "Participants should understand that personal data may be processed in circumstances recognised by the legal framework and that not every processing activity should automatically be treated as consent-based processing. Basic knowledge of purpose limitation, lawful processing, organisational functions and the distinction between primary and secondary uses of data is useful before studying specified legitimate-use situations.",
  12: "Participants should understand the role of a Data Fiduciary and have basic knowledge of privacy governance, cybersecurity, data accuracy, retention, erasure, grievance handling and third-party management. They should recognise that compliance requires coordinated organisational processes, technical safeguards, accountability and evidence rather than a single privacy policy.",
  13: "Participants should understand the concepts of personal data, consent and Data Fiduciary responsibilities before examining requirements relating to children. They should also have a basic awareness of digital platforms and services used by children, age-related controls, parental involvement, online tracking, targeted advertising and the additional privacy risks associated with processing children's data.",
  14: "Participants should understand the basic responsibilities of a Data Fiduciary, organisational risk management and privacy governance. Familiarity with concepts such as Data Protection Officer, Data Protection Impact Assessment, independent audit, algorithmic systems, senior management oversight and enhanced compliance requirements will help participants understand the additional responsibilities applicable to a Significant Data Fiduciary.",
  15: "Participants should understand who a Data Principal is and how an organisation collects and maintains personal data about individuals. Basic familiarity with access, correction, erasure, grievance redressal, nomination, identity verification and customer-service request mechanisms will help participants understand how Data Principal rights are exercised and fulfilled.",
  16: "Participants should first understand the rights available to Data Principals and the corresponding responsibilities of Data Fiduciaries. They should also have basic awareness of identity verification, accurate information, impersonation, fraudulent requests and misuse of digital services so that they can understand why individuals must exercise their rights and interactions responsibly.",
  17: "Participants should have a basic understanding of data flows, cloud computing, remote access, international vendors and cross-border technology operations. They should be able to distinguish between where data is stored and where it may be accessed or processed, and should understand the importance of contracts, access controls, encryption, logging and third-party governance in international data environments.",
  18: "Participants should understand the general applicability of the DPDP framework and the obligations normally imposed on organisations before studying exemptions. They should recognise that an exemption is a specific legal provision applicable to defined circumstances and is not a general permission to ignore privacy, security or governance responsibilities.",
  19: "Participants should have a basic understanding of cybersecurity principles including authentication, access control, passwords, MFA, encryption, backups, logging, monitoring, vulnerability management and incident response. Familiarity with organisational IT environments and common cyber risks will help participants understand how reasonable security safeguards protect personal data against unauthorised access, disclosure, alteration, loss or compromise.",
  20: "Participants should understand basic cybersecurity incidents and how personal data can be exposed through hacking, malware, accidental disclosure, lost devices, misconfiguration, insider activity or compromised third parties. Basic knowledge of incident detection, containment, evidence preservation, forensic investigation, impact assessment, notification and remediation will help participants understand an effective personal-data breach response.",
  21: "Participants should have a basic understanding of the DPDP Act, the responsibilities of Data Fiduciaries and the importance of regulatory compliance. They should also understand basic concepts such as inquiry, evidence, regulatory communication, compliance directions, record preservation and organisational response so that they can appreciate the role of the Data Protection Board.",
  22: "Participants should understand consent, consent records, withdrawal of consent and the importance of maintaining reliable evidence of an individual's consent choices. Basic familiarity with digital identity, APIs, interoperability, dashboards and privacy-management systems will help participants understand how a Consent Manager can support the management and exchange of consent-related information.",
  23: "Participants should understand organisational privacy governance and the responsibilities of a Data Fiduciary before studying the role of the Data Protection Officer and designated contact mechanisms. Basic knowledge of compliance reporting, grievance handling, data-protection rights, incident management, audits, escalation and management oversight will help participants understand the responsibilities and organisational position of the DPO.",
  24: "Participants should understand the rights of Data Principals and the importance of providing an accessible mechanism through which privacy-related complaints can be submitted and resolved. Basic familiarity with customer-service workflows, identity verification, case ownership, escalation, response tracking, documentation and audit trails will help participants design an effective grievance-redressal process.",
  25: "Participants should understand the role of the Data Protection Board, the obligations of Data Fiduciaries and the importance of maintaining evidence of compliance. They should have a basic understanding of regulatory inquiries, evidence preservation, legal review, organisational escalation, corrective action and communication with regulators before studying enforcement procedures.",
  26: "Participants should understand the major obligations imposed on Data Fiduciaries, the importance of reasonable security safeguards and the consequences of non-compliance. Basic knowledge of enterprise risk management, control failures, financial exposure, risk registers, management accountability and remediation will help participants understand why privacy compliance must be treated as a strategic organisational risk.",
  27: "Participants should understand the data lifecycle, including collection, use, storage, sharing, retention and eventual deletion. They should have basic familiarity with databases, applications, backups, cloud storage, spreadsheets, analytics environments and third-party systems, as well as the concepts of purpose limitation, retention periods and secure deletion.",
  28: "Participants should understand the basic responsibilities of a Data Fiduciary, organisational risk management, cybersecurity controls and privacy compliance. Familiarity with risk assessments, audits, DPIAs, residual risk, remediation plans, governance committees and accountability mechanisms will help participants understand how privacy risks are identified, assessed, documented and managed.",
  29: "Participants should have a working understanding of the major concepts covered in the preceding modules, including Data Principals, Data Fiduciaries, Data Processors, consent, rights, security safeguards, breaches, retention, governance and enforcement. They should be ready to connect these individual requirements into an integrated organisational compliance programme involving people, processes, technology, documentation, training, testing and continuous improvement.",
  30: "Participants should have completed or understood the preceding modules and should be familiar with the major DPDP compliance areas, including data inventory, purposes, consent, notices, rights, processors, security, breach response, retention, governance, DPIA, audit and regulatory readiness. They should be able to review organisational practices against defined requirements, identify evidence and control gaps, assess risk and recommend practical remediation actions.",
};

export function modulePrerequisite(moduleNumber: number): string | null {
  return MODULE_PREREQUISITES[moduleNumber] ?? null;
}
