import type { ComplianceSeverity } from "./types";

export type ComplianceRuleDefinition = {
  id: string;
  jurisdiction: string;
  severity: ComplianceSeverity;
  description: string;
  remediation: string;
};

export const COMPLIANCE_RULES = {
  POLICY_IDENTITY_MISSING: {
    id: "POLICY_IDENTITY_MISSING",
    jurisdiction: "common",
    severity: "error",
    description: "The policy is missing a name or stable identity.",
    remediation: "Give the policy a name and publish from an organization-owned website.",
  },
  POLICY_WEBSITE_MISSING: {
    id: "POLICY_WEBSITE_MISSING",
    jurisdiction: "common",
    severity: "error",
    description: "The policy is not associated with a website.",
    remediation: "Attach the policy to an organization-owned website before publishing.",
  },
  PURPOSE_REQUIRED_MISSING: {
    id: "PURPOSE_REQUIRED_MISSING",
    jurisdiction: "common",
    severity: "error",
    description: "A policy cannot be published without at least one purpose.",
    remediation: "Attach one or more purposes to this policy version.",
  },
  PURPOSE_WITHOUT_DESCRIPTION: {
    id: "PURPOSE_WITHOUT_DESCRIPTION",
    jurisdiction: "common",
    severity: "error",
    description: "An attached purpose has no visitor-facing description.",
    remediation: "Add a clear purpose description before publishing.",
  },
  PURPOSE_WITHOUT_LEGAL_BASIS: {
    id: "PURPOSE_WITHOUT_LEGAL_BASIS",
    jurisdiction: "common",
    severity: "warning",
    description: "An attached purpose does not declare a lawful/legal basis.",
    remediation: "Set a lawful basis from the configured catalog for this purpose.",
  },
  VENDOR_WITHOUT_PRIVACY_URL: {
    id: "VENDOR_WITHOUT_PRIVACY_URL",
    jurisdiction: "common",
    severity: "error",
    description: "A vendor attached through this policy has no privacy policy URL.",
    remediation: "Add a privacy policy URL for each vendor shown in the notice.",
  },
  TRACKER_UNMAPPED: {
    id: "TRACKER_UNMAPPED",
    jurisdiction: "common",
    severity: "error",
    description: "An optional active tracker has no valid purpose or vendor mapping.",
    remediation: "Map the tracker to a purpose and vendor, disable it, or archive it.",
  },
  TRACKER_ESSENTIAL_NOT_REQUIRED: {
    id: "TRACKER_ESSENTIAL_NOT_REQUIRED",
    jurisdiction: "common",
    severity: "error",
    description: "A tracker is marked essential but is not linked to a required/necessary purpose.",
    remediation: "Only classify a tracker as essential when it is mapped to a required purpose. Client-only essential flags are not accepted.",
  },
  TRACKER_IGNORED_STILL_ACTIVE: {
    id: "TRACKER_IGNORED_STILL_ACTIVE",
    jurisdiction: "common",
    severity: "error",
    description: "An ignored scanner finding is still an active executable tracker.",
    remediation: "Disable or archive ignored detections. Ignoring a finding does not authorize execution.",
  },
  NOTICE_TITLE_MISSING: {
    id: "NOTICE_TITLE_MISSING",
    jurisdiction: "common",
    severity: "error",
    description: "The published notice has no title.",
    remediation: "Set a banner title on the version that will be published.",
  },
  NOTICE_DESCRIPTION_MISSING: {
    id: "NOTICE_DESCRIPTION_MISSING",
    jurisdiction: "common",
    severity: "error",
    description: "The published notice has no description.",
    remediation: "Set banner description text on the version that will be published.",
  },
  NOTICE_PRIVACY_POLICY_MISSING: {
    id: "NOTICE_PRIVACY_POLICY_MISSING",
    jurisdiction: "common",
    severity: "warning",
    description: "The notice does not include a privacy policy URL.",
    remediation: "Add a privacy policy URL so visitors can read the full notice.",
  },
  GDPR_PREGRANTED_OPTIONAL_CONSENT: {
    id: "GDPR_PREGRANTED_OPTIONAL_CONSENT",
    jurisdiction: "gdpr",
    severity: "error",
    description: "Optional processing is configured as pre-granted.",
    remediation: "Set the default consent state to denied/none. Non-essential processing must wait for an affirmative choice.",
  },
  GDPR_MISSING_WITHDRAWAL: {
    id: "GDPR_MISSING_WITHDRAWAL",
    jurisdiction: "gdpr",
    severity: "error",
    description: "Withdrawal is not as available as the consent action.",
    remediation: "Show Reject all and keep the preference-center widget enabled so consent can be withdrawn as easily as it is given.",
  },
  GDPR_MISSING_RIGHTS: {
    id: "GDPR_MISSING_RIGHTS",
    jurisdiction: "gdpr",
    severity: "error",
    description: "Required GDPR rights are not represented in this configuration.",
    remediation: "Keep the product privacy-rights workflow enabled for access, rectification, erasure, restriction, objection, portability, and withdrawal.",
  },
  GDPR_SPECIAL_CATEGORY_INCOMPLETE: {
    id: "GDPR_SPECIAL_CATEGORY_INCOMPLETE",
    jurisdiction: "gdpr",
    severity: "error",
    description: "Special-category processing is configured without a corresponding condition.",
    remediation: "Record the Article 9 condition or disable special-category processing on this policy.",
  },
  GDPR_CHILD_CONFIG_MISSING: {
    id: "GDPR_CHILD_CONFIG_MISSING",
    jurisdiction: "gdpr",
    severity: "error",
    description: "Child-directed processing is configured without age or guardian controls.",
    remediation: "Set an age threshold and guardian-consent requirement, or disable child-directed processing.",
  },
  GDPR_AUTOMATED_DECISION_MISSING: {
    id: "GDPR_AUTOMATED_DECISION_MISSING",
    jurisdiction: "gdpr",
    severity: "error",
    description: "Automated decision-making or profiling is configured without disclosure.",
    remediation: "Disclose automated decision-making in the notice, or disable that declaration.",
  },
  GDPR_TRACKER_ALLOWED_WITHOUT_CONSENT: {
    id: "GDPR_TRACKER_ALLOWED_WITHOUT_CONSENT",
    jurisdiction: "gdpr",
    severity: "error",
    description: "A consent-required tracker would run as allowed without consent.",
    remediation: "Map the tracker to a consent purpose and do not mark optional advertising/analytics trackers as essential.",
  },
  DPDP_NOTICE_MISSING_CATEGORY: {
    id: "DPDP_NOTICE_MISSING_CATEGORY",
    jurisdiction: "dpdp",
    severity: "error",
    description: "A consent-required purpose is missing personal-data categories.",
    remediation: "List the personal-data categories processed for each consent-required purpose.",
  },
  DPDP_NOTICE_MISSING_FIDUCIARY: {
    id: "DPDP_NOTICE_MISSING_FIDUCIARY",
    jurisdiction: "dpdp",
    severity: "error",
    description: "Data Fiduciary identity or grievance contact is missing.",
    remediation: "Set organization name plus DPO or grievance-officer contact details.",
  },
  DPDP_PREGRANTED_CONSENT: {
    id: "DPDP_PREGRANTED_CONSENT",
    jurisdiction: "dpdp",
    severity: "error",
    description: "Consent-required purposes are pre-granted.",
    remediation: "Set default consent to none/denied and keep purposes independently selectable.",
  },
  DPDP_MISSING_WITHDRAWAL: {
    id: "DPDP_MISSING_WITHDRAWAL",
    jurisdiction: "dpdp",
    severity: "error",
    description: "A withdrawal mechanism is not configured.",
    remediation: "Enable Reject all or the preference-center widget so consent can be withdrawn.",
  },
  DPDP_CHILD_CONFIG_MISSING: {
    id: "DPDP_CHILD_CONFIG_MISSING",
    jurisdiction: "dpdp",
    severity: "error",
    description: "Child processing is enabled without age or guardian configuration.",
    remediation: "Configure age/guardian handling or disable child-directed processing.",
  },
  DPDP_CONSENT_MANAGER_CONFIG_MISSING: {
    id: "DPDP_CONSENT_MANAGER_CONFIG_MISSING",
    jurisdiction: "dpdp",
    severity: "error",
    description: "Consent Manager mode is enabled but required configuration is missing.",
    remediation: "Supply the configured Consent Manager fields. This is a configuration requirement, not a legal certification.",
  },
  CCPA_MISSING_DO_NOT_SELL_SHARE: {
    id: "CCPA_MISSING_DO_NOT_SELL_SHARE",
    jurisdiction: "ccpa",
    severity: "error",
    description: "Do Not Sell / Do Not Share is not configured.",
    remediation: "Enable a Do Not Sell or Do Not Share control, or attach a sale/share purpose.",
  },
  CCPA_GPC_RUNTIME_UNSUPPORTED: {
    id: "CCPA_GPC_RUNTIME_UNSUPPORTED",
    jurisdiction: "ccpa",
    severity: "warning",
    description: "This runtime does not honor Global Privacy Control (Sec-GPC).",
    remediation: "Do not claim GPC support. Add runtime GPC handling before treating GPC as implemented.",
  },
  CCPA_GPC_CLAIMED_WITHOUT_RUNTIME: {
    id: "CCPA_GPC_CLAIMED_WITHOUT_RUNTIME",
    jurisdiction: "ccpa",
    severity: "error",
    description: "The policy claims GPC is honored, but the runtime does not implement Sec-GPC.",
    remediation: "Disable the GPC-honored declaration until the SDK actually reads and applies Sec-GPC.",
  },
  CCPA_MISSING_OPT_OUT: {
    id: "CCPA_MISSING_OPT_OUT",
    jurisdiction: "ccpa",
    severity: "error",
    description: "An opt-out path is not available in the published notice.",
    remediation: "Show Reject all or a preference-center opt-out control.",
  },
  CCPA_SALE_OPT_OUT_UNCONFIGURED: {
    id: "CCPA_SALE_OPT_OUT_UNCONFIGURED",
    jurisdiction: "ccpa",
    severity: "error",
    description: "A California Do Not Sell control is not configured.",
    remediation: "Enable the Do Not Sell preference-center control for California-configured policies.",
  },
  CCPA_SHARE_OPT_OUT_UNCONFIGURED: {
    id: "CCPA_SHARE_OPT_OUT_UNCONFIGURED",
    jurisdiction: "ccpa",
    severity: "error",
    description: "A California Do Not Share control is not configured.",
    remediation: "Enable the Do Not Share preference-center control for California-configured policies.",
  },
  CCPA_SENSITIVE_PI_CONTROL_UNCONFIGURED: {
    id: "CCPA_SENSITIVE_PI_CONTROL_UNCONFIGURED",
    jurisdiction: "ccpa",
    severity: "error",
    description: "Sensitive PI processing is indicated without a Limit Sensitive PI control.",
    remediation: "Enable Limit Use of Sensitive Personal Information, or mark the processing as not applicable.",
  },
  CCPA_OPT_OUT_VENDOR_MAPPING_MISSING: {
    id: "CCPA_OPT_OUT_VENDOR_MAPPING_MISSING",
    jurisdiction: "ccpa",
    severity: "error",
    description: "A vendor has no California sale/share classification.",
    remediation: "Set each vendor to sale, sharing, both, or neither. Unknown is not a legal conclusion.",
  },
  CCPA_OPT_OUT_TRACKER_MAPPING_MISSING: {
    id: "CCPA_OPT_OUT_TRACKER_MAPPING_MISSING",
    jurisdiction: "ccpa",
    severity: "error",
    description: "An optional tracker has no California sale/share classification.",
    remediation: "Classify the tracker, or inherit a vendor classification. Do not leave optional trackers unknown on California policies.",
  },
  CCPA_SENSITIVE_PI_UNCONFIGURED: {
    id: "CCPA_SENSITIVE_PI_UNCONFIGURED",
    jurisdiction: "ccpa",
    severity: "error",
    description: "Sensitive personal information is indicated without a limitation configuration.",
    remediation: "Limit sensitive PI purposes or record the sensitive-PI configuration.",
  },
  CCPA_MINOR_CONFIG_MISSING: {
    id: "CCPA_MINOR_CONFIG_MISSING",
    jurisdiction: "ccpa",
    severity: "error",
    description: "Minor-directed processing is configured without age/guardian controls.",
    remediation: "Configure minor handling or disable child-directed processing.",
  },
  CCPA_OPT_OUT_PROPAGATION_UNSUPPORTED: {
    id: "CCPA_OPT_OUT_PROPAGATION_UNSUPPORTED",
    jurisdiction: "ccpa",
    severity: "warning",
    description: "Opt-out signal encoding exists, but full opt-out propagation is not implemented as a runtime guarantee.",
    remediation: "Treat GPP/IAB signals as publication aids only. Do not mark propagation as complete unless the runtime actually forwards opt-out.",
  },
  LGPD_MISSING_RIGHT: {
    id: "LGPD_MISSING_RIGHT",
    jurisdiction: "lgpd",
    severity: "error",
    description: "A required LGPD right is not represented.",
    remediation: "Keep access, correction, deletion, portability, and withdrawal represented in the privacy-rights workflow.",
  },
  LGPD_MISSING_WITHDRAWAL: {
    id: "LGPD_MISSING_WITHDRAWAL",
    jurisdiction: "lgpd",
    severity: "error",
    description: "Consent revocation is not available in the published configuration.",
    remediation: "Enable Reject all or the preference-center widget.",
  },
  LGPD_CHILD_CONFIG_MISSING: {
    id: "LGPD_CHILD_CONFIG_MISSING",
    jurisdiction: "lgpd",
    severity: "error",
    description: "Child or adolescent processing is configured without best-interest/guardian controls.",
    remediation: "Configure age/guardian handling or disable child-directed processing.",
  },
  LGPD_TRANSFER_MECHANISM_MISSING: {
    id: "LGPD_TRANSFER_MECHANISM_MISSING",
    jurisdiction: "lgpd",
    severity: "error",
    description: "International processing is indicated without a transfer mechanism.",
    remediation: "Record the transfer mechanism or disable the international-transfer declaration. The product cannot invent a safeguard.",
  },
  LGPD_AUTOMATED_DECISION_MISSING: {
    id: "LGPD_AUTOMATED_DECISION_MISSING",
    jurisdiction: "lgpd",
    severity: "error",
    description: "Automated decision-making is configured without disclosure.",
    remediation: "Disclose automated decisions in the notice or disable that declaration.",
  },
  CHILD_DIRECTED_WITHOUT_CONTROLS: {
    id: "CHILD_DIRECTED_WITHOUT_CONTROLS",
    jurisdiction: "common",
    severity: "error",
    description: "Child-directed processing, tracking, or advertising is configured without controls.",
    remediation: "Set age and guardian configuration, and do not enable targeted advertising for child-directed properties.",
  },
  CHILD_PROTECTION_CONFIG_MISSING: {
    id: "CHILD_PROTECTION_CONFIG_MISSING",
    jurisdiction: "common",
    severity: "error",
    description: "Child-directed or child-protected processing is enabled without a complete website child-protection configuration.",
    remediation: "Set a minimum age, age-assurance requirement, restricted purposes, and guardian workflow where the website is child-directed.",
  },
  AGE_ASSURANCE_REQUIRED: {
    id: "AGE_ASSURANCE_REQUIRED",
    jurisdiction: "common",
    severity: "error",
    description: "Child-protected processing is configured without age assurance.",
    remediation: "Enable age assurance and set the applicable minimum-age threshold for this website.",
  },
  GUARDIAN_WORKFLOW_MISSING: {
    id: "GUARDIAN_WORKFLOW_MISSING",
    jurisdiction: "common",
    severity: "error",
    description: "A child-directed website does not require a guardian authorization workflow.",
    remediation: "Enable guardian consent for child-directed properties. Email contact proof is not legal authority.",
  },
  CHILD_RESTRICTED_PURPOSE_UNCONTROLLED: {
    id: "CHILD_RESTRICTED_PURPOSE_UNCONTROLLED",
    jurisdiction: "common",
    severity: "error",
    description: "An optional child-sensitive purpose is not listed in the website restricted-purpose controls.",
    remediation: "Add advertising, profiling, social, and other child-sensitive purpose keys to the website restricted-purpose list.",
  },
  CHILD_ADVERTISING_CONTROL_MISSING: {
    id: "CHILD_ADVERTISING_CONTROL_MISSING",
    jurisdiction: "common",
    severity: "error",
    description: "Targeted advertising is attached to a child-protected website without a restricted advertising control.",
    remediation: "Include advertising/ads/targeting purpose keys in child-protection restricted purposes so those trackers stay blocked until assurance unlocks them.",
  },
  SENSITIVE_DATA_UNCONFIGURED: {
    id: "SENSITIVE_DATA_UNCONFIGURED",
    jurisdiction: "common",
    severity: "error",
    description: "Sensitive or special-category data is indicated without jurisdiction-appropriate configuration.",
    remediation: "Add the jurisdiction-specific sensitive-data condition or remove the sensitive-data indication.",
  },
  TRANSFER_MECHANISM_MISSING: {
    id: "TRANSFER_MECHANISM_MISSING",
    jurisdiction: "common",
    severity: "warning",
    description: "A vendor country suggests international processing, but no transfer mechanism is recorded.",
    remediation: "Record destination/transfer metadata where the model supports it. Do not invent a mechanism.",
  },
  VENDOR_ROLE_MISSING: {
    id: "VENDOR_ROLE_MISSING",
    jurisdiction: "common",
    severity: "error",
    description: "A vendor attached to this policy has no processing role.",
    remediation: "Set the vendor role (controller, processor, subprocessor, or equivalent) before publishing.",
  },
  PROCESSING_ACTIVITY_PURPOSE_MISSING: {
    id: "PROCESSING_ACTIVITY_PURPOSE_MISSING",
    jurisdiction: "common",
    severity: "error",
    description: "A processing activity is not linked to a purpose.",
    remediation: "Attach each processing activity to a purpose from the existing purpose registry.",
  },
  PROCESSING_ACTIVITY_DATA_CATEGORY_MISSING: {
    id: "PROCESSING_ACTIVITY_DATA_CATEGORY_MISSING",
    jurisdiction: "common",
    severity: "error",
    description: "A processing activity does not list personal-data categories.",
    remediation: "Record the data categories processed in this activity.",
  },
  TRANSFER_DESTINATION_MISSING: {
    id: "TRANSFER_DESTINATION_MISSING",
    jurisdiction: "common",
    severity: "error",
    description: "A cross-border transfer record has no destination country or region.",
    remediation: "Set the destination country or region. The product cannot invent a destination.",
  },
  TRANSFER_SAFEGUARD_MISSING: {
    id: "TRANSFER_SAFEGUARD_MISSING",
    jurisdiction: "common",
    severity: "error",
    description: "A transfer mechanism that requires additional safeguards has none recorded.",
    remediation: "Record the safeguard description for SCCs, BCRs, derogations, or other mechanisms.",
  },
  SUBPROCESSOR_RELATIONSHIP_MISSING: {
    id: "SUBPROCESSOR_RELATIONSHIP_MISSING",
    jurisdiction: "common",
    severity: "error",
    description: "A subprocessor is recorded without a processor/subprocessor relationship.",
    remediation: "Link the subprocessor to its parent processor in vendor relationships.",
  },
  VENDOR_DPA_CONFIGURATION_MISSING: {
    id: "VENDOR_DPA_CONFIGURATION_MISSING",
    jurisdiction: "common",
    severity: "error",
    description: "A processor or subprocessor has no DPA status recorded.",
    remediation: "Record DPA status/reference. A field in this product is not proof that a DPA exists.",
  },
  INACTIVE_VENDOR_REFERENCED: {
    id: "INACTIVE_VENDOR_REFERENCED",
    jurisdiction: "common",
    severity: "error",
    description: "An inactive or archived vendor is still referenced by this policy.",
    remediation: "Remove the vendor from the draft policy, remap trackers, or restore the vendor before publishing.",
  },
  TRANSFER_REVIEW_EXPIRED: {
    id: "TRANSFER_REVIEW_EXPIRED",
    jurisdiction: "common",
    severity: "warning",
    description: "A transfer record is past its review date.",
    remediation: "Review the transfer record. An expired review date is an operational warning, not a legal determination.",
  },
} as const satisfies Record<string, ComplianceRuleDefinition>;

export type ComplianceRuleId = keyof typeof COMPLIANCE_RULES;

export function getComplianceRule(id: string): ComplianceRuleDefinition | null {
  return (COMPLIANCE_RULES as Record<string, ComplianceRuleDefinition>)[id] ?? null;
}
