import type { TrackerRule } from "./enforcement";

export const BUILTIN_TRACKER_CATALOG: TrackerRule[] = [
  {
    id: "builtin-google-analytics",
    name: "Google Analytics",
    type: "script",
    domain: "google-analytics.com",
    identifier: "google-analytics.com",
    purposeKey: "analytics",
    purposeId: null,
    vendorId: null,
    isEssential: false,
    status: "active",
    category: "analytics",
    cookieNames: ["_ga", "_ga_*", "_gid", "_gat", "_gat_*"],
    storageTypes: ["cookie", "localStorage"],
    localStorageKeys: ["_ga", "_ga_*"],
    sessionStorageKeys: [],
    indexedDbNames: [],
    scriptUrlPatterns: ["google-analytics.com", "googletagmanager.com/gtag/js"],
    iframeUrlPatterns: [],
    pixelUrlPatterns: ["google-analytics.com/collect", "google-analytics.com/g/collect"],
    party: "third-party",
    duration: "Up to 2 years; vendor configuration may vary",
    deletionBehavior: "Delete matching first-party cookies and storage keys.",
  },
  {
    id: "builtin-google-ads",
    name: "Google Ads",
    type: "pixel",
    domain: "doubleclick.net",
    identifier: "doubleclick.net",
    purposeKey: "marketing",
    purposeId: null,
    vendorId: null,
    isEssential: false,
    status: "active",
    category: "advertising",
    cookieNames: ["_gcl_*", "IDE", "test_cookie"],
    storageTypes: ["cookie"],
    localStorageKeys: [],
    sessionStorageKeys: [],
    indexedDbNames: [],
    scriptUrlPatterns: ["googleadservices.com", "doubleclick.net"],
    iframeUrlPatterns: ["doubleclick.net"],
    pixelUrlPatterns: ["googleadservices.com", "doubleclick.net"],
    party: "third-party",
    duration: "Vendor-defined",
    deletionBehavior: "Delete accessible first-party conversion cookies.",
  },
  {
    id: "builtin-meta-pixel",
    name: "Meta Pixel",
    type: "pixel",
    domain: "facebook.com",
    identifier: "connect.facebook.net",
    purposeKey: "marketing",
    purposeId: null,
    vendorId: null,
    isEssential: false,
    status: "active",
    category: "advertising",
    cookieNames: ["_fbp", "_fbc"],
    storageTypes: ["cookie"],
    localStorageKeys: [],
    sessionStorageKeys: [],
    indexedDbNames: [],
    scriptUrlPatterns: ["connect.facebook.net", "facebook.com/tr"],
    iframeUrlPatterns: ["facebook.com"],
    pixelUrlPatterns: ["facebook.com/tr", "facebook.com/tr/"],
    party: "third-party",
    duration: "Vendor-defined",
    deletionBehavior: "Delete accessible first-party Meta attribution cookies.",
  },
  {
    id: "builtin-youtube",
    name: "YouTube Embed",
    type: "iframe",
    domain: "youtube.com",
    identifier: "youtube.com/embed",
    purposeKey: "marketing",
    purposeId: null,
    vendorId: null,
    isEssential: false,
    status: "active",
    category: "embedded-content",
    cookieNames: [],
    storageTypes: ["cookie", "localStorage"],
    localStorageKeys: [],
    sessionStorageKeys: [],
    indexedDbNames: [],
    scriptUrlPatterns: [],
    iframeUrlPatterns: ["youtube.com/embed", "youtube-nocookie.com/embed"],
    party: "third-party",
    duration: "Vendor-defined",
    deletionBehavior: "Unload blocked embeds; third-party cookies are not script-accessible.",
  },
  {
    id: "builtin-google-maps",
    name: "Google Maps",
    type: "iframe",
    domain: "google.com",
    identifier: "google.com/maps",
    purposeKey: "functionality",
    purposeId: null,
    vendorId: null,
    isEssential: false,
    status: "active",
    category: "embedded-content",
    cookieNames: [],
    storageTypes: ["cookie"],
    localStorageKeys: [],
    sessionStorageKeys: [],
    indexedDbNames: [],
    scriptUrlPatterns: ["maps.googleapis.com"],
    iframeUrlPatterns: ["google.com/maps"],
    party: "third-party",
    duration: "Vendor-defined",
    deletionBehavior: "Unload blocked embeds; third-party cookies are not script-accessible.",
  },
  {
    id: "builtin-google-tag-manager",
    name: "Google Tag Manager container",
    type: "script",
    domain: "googletagmanager.com",
    identifier: "googletagmanager.com/gtm.js",
    purposeKey: "analytics",
    purposeId: null,
    vendorId: null,
    isEssential: false,
    status: "active",
    category: "tag-manager",
    cookieNames: [],
    storageTypes: ["cookie"],
    localStorageKeys: [],
    sessionStorageKeys: [],
    indexedDbNames: [],
    scriptUrlPatterns: ["googletagmanager.com/gtm.js", "googletagmanager.com/gtag/js"],
    iframeUrlPatterns: [],
    pixelUrlPatterns: [],
    party: "third-party",
    duration: "Vendor-defined",
    deletionBehavior:
      "Pause the GTM/gtag loader URL when the mapped purpose is denied. This does not control tags already configured inside a GTM container.",
  },
];

export function findBuiltinTracker(value: string | null | undefined): TrackerRule | null {
  const normalized = String(value ?? "").toLowerCase();
  if (!normalized) return null;
  return (
    BUILTIN_TRACKER_CATALOG.find((rule) => {
      const candidates = [
        rule.domain,
        rule.identifier,
        ...(rule.scriptUrlPatterns ?? []),
        ...(rule.iframeUrlPatterns ?? []),
        ...(rule.pixelUrlPatterns ?? []),
      ].filter(Boolean) as string[];
      return candidates.some((candidate) =>
        normalized.includes(candidate.toLowerCase().replaceAll("*", "")),
      );
    }) ?? null
  );
}
