import Link from "next/link";
import { desc, eq } from "drizzle-orm";
import { requireDashboardContext } from "@/lib/bootstrap-current-context";
import { db } from "@/db";
import { consentSessions } from "@/db/schema/consent-sessions";
import { websites } from "@/db/schema/websites";
import { consentRecords } from "@/db/schema/consent-records";
import { Badge } from "@/components/ui/badge";
import { Card } from "@/components/ui/card";
import { PageHeader } from "@/components/ui/page-header";
export default async function ConsentSessionsPage() { const context = await requireDashboardContext(); const rows = await db.select({ session: consentSessions, websiteName: websites.name, consentId: consentRecords.consentId }).from(consentSessions).innerJoin(websites, eq(consentSessions.websiteId, websites.id)).leftJoin(consentRecords, eq(consentSessions.consentRecordId, consentRecords.id)).where(eq(consentSessions.organizationId, context.organization.id)).orderBy(desc(consentSessions.createdAt)).limit(250); return <div className="page-wrap space-y-6"><PageHeader title="Consent sessions" description="Short-lived sessions group consent decisions with the policy version and cryptographic proof."/><Card><div className="card-section-header"><h2 className="font-semibold">Recent sessions</h2><span className="text-sm text-[var(--muted-foreground)]">{rows.length}</span></div><div className="table-scroll"><table className="min-w-full text-sm"><thead><tr className="border-b bg-[var(--muted)]/60">{["Site", "Consent", "Policy version", "Status", "Decisions", "Issued", "Expires"].map((x)=><th className="p-3 text-left" key={x}>{x}</th>)}</tr></thead><tbody>{rows.map(({session,websiteName,consentId})=>{const status=session.revokedAt?"revoked":session.expiresAt<=new Date()?"expired":session.status;return <tr className="border-t" key={session.id}><td className="p-3">{websiteName}</td><td className="p-3">{consentId?<Link className="underline" href={`/dashboard/consent/${encodeURIComponent(consentId)}`}>{consentId}</Link>:"Pending decision"}</td><td className="p-3">{session.policyVersionId.slice(0,8)}</td><td className="p-3"><Badge variant={status==="active"?"success":"neutral"} size="sm">{status}</Badge></td><td className="p-3">{session.decisionCount}</td><td className="p-3">{session.createdAt.toLocaleString()}</td><td className="p-3">{session.expiresAt.toLocaleString()}</td></tr>})}{rows.length===0&&<tr><td className="p-8 text-center text-[var(--muted-foreground)]" colSpan={7}>No consent sessions have been recorded yet.</td></tr>}</tbody></table></div></Card></div>; }
